[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "mentflow"
version = "0.0.2"
dependencies = [
    "gitpython",
    "hydra-core",
    "matplotlib",
    "numpy",
    "pandas",
    "pot",
    "psdist @ git+https://github.com/austin-hoover/psdist@3a9409d4821f836abee4a1e9c43d4519d9a37e1e",
    "scipy>=1.10",
    "scikit-image",
    "torch",
    "tqdm",
    "zuko",
]
requires-python = ">=3.11"
authors = [
  {name = "Austin Hoover"},
]
description = "Maximum entropy tomography using normalizing flows"
readme = "README.md"

[project.urls]
Repository = "https://github.com/austin-hoover/ment-flow.git"
