[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "mentflow"
version = "0.0.1"
dependencies = [
    "gitpython",
    "hydra-core",
    "matplotlib",
    "numpy",
    "pandas",
    "pot",
    "proplot @ git+https://github.com/austin-hoover/proplot@cfd060e2d6c922c7d80d21d23484454e11b17ab7",
    "psdist @ git+https://github.com/austin-hoover/psdist@3abd7da8a8cfd83be859e7ad2fcab567dda1cea0",
    "scipy>=1.10",
    "scikit-image",
    "torch",
    "tqdm",
    "zuko",
]
requires-python = ">=3.11"
authors = [
  {name = "Austin Hoover"},
]
description = "Maximum entropy tomography using normalizing flows"
readme = "README.md"

[project.urls]
Repository = "https://github.com/austin-hoover/ment-flow.git"
